name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: nginx:stable-alpine
      ports:
        - 80:80
    steps:
      - name: Check the server
        run: netstat -tulpn | grep LISTEN