name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: nginx
      ports:
        - 80
    steps:
      - name: Check the server
        run: wget localhost