name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: nginx:stable-alpine
      ports:
        - 80:80
    steps:
      - name: Wait little bit
        run: sleep 5
      - name: Check the ports
        run: netstat -tulpn | grep LISTEN | awk '{print $4}'
      - name: Check the server
        run: curl $(netstat -tulpn | grep LISTEN | awk '{print $4}')