name: Hello World Container Github Actions Demo
on: [push]
jobs:
  run-hello-world-container:
    runs-on: github-action
    container:
      image: hello-world
    steps:
    - name: Run echo
      run: |
        echo "hello world!"